sudo: false
dist: trusty
group: deprecated-2017Q4 # To fix NPM timeout errors
language: ruby
rvm:
- 2.4.3
if: branch = master OR repo =~ /-stage/
before_install:
- echo -e "machine github.com\n login $GH_TOKEN" >> ~/.netrc
- git submodule add https://github.com/NetAppDocs/jekyll dependencies/jekyll
- gem update --system && gem install bundler && gem update bundler
# Custom section for Cloud Volumes structure
- sed -i 's/`search\.html`/`https\:\/\/docs\.netapp\.com\/us-en\/'$REPO_NAME'\/search\.html`/g' ./dependencies/jekyll/webpack/components/Search.js
- cp -rl dependencies/jekyll/search.html ./cloud\_volumes\_ontap/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ cloud\_volumes\_ontap\/search\.html/g' ./cloud\_volumes\_ontap/search.html
- cp -rl dependencies/jekyll/search.html ./cloud\_volumes\_service/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ cloud\_volumes\_service\/search\.html/g' ./cloud\_volumes\_service/search.html
- cp -rl dependencies/jekyll/search.html ./genomics/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ genomics\/search\.html/g' ./genomics/search.html
- cp -rl dependencies/jekyll/search.html ./NPS/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ NPS\/search\.html/g' ./NPS/search.html
- cp -rl dependencies/jekyll/search.html ./oracle/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ oracle\/search\.html/g' ./oracle/search.html
- cp -rl dependencies/jekyll/search.html ./mysql/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ mysql\/search\.html/g' ./mysql/search.html
- mv dependencies/jekyll/prod-build.sh ./ && ./prod-build.sh
script:
- bundle exec rake deploy
